include_guard(GLOBAL)
option(CC_NIRI_USE_RUST_FOCUS_RING_CORE "Use Rust Focus Ring numeric snapshots and geometry" ON)
message(STATUS "CC-Niri Rust Focus Ring Core backend: ${CC_NIRI_USE_RUST_FOCUS_RING_CORE}")
add_library(cc-niri-focus-ring-reference STATIC "${CMAKE_CURRENT_LIST_DIR}/../focus-ring/FocusRingCore.cpp")
set_target_properties(cc-niri-focus-ring-reference PROPERTIES AUTOMOC OFF POSITION_INDEPENDENT_CODE ON)
target_include_directories(cc-niri-focus-ring-reference PUBLIC "${CMAKE_CURRENT_LIST_DIR}/../focus-ring" "${CMAKE_CURRENT_LIST_DIR}/../rust/include")
add_library(cc-niri-focus-ring-core-backend INTERFACE)
target_link_libraries(cc-niri-focus-ring-core-backend INTERFACE cc-niri-focus-ring-reference)
target_compile_definitions(cc-niri-focus-ring-core-backend INTERFACE
    CC_NIRI_USE_RUST_FOCUS_RING_CORE=$<BOOL:${CC_NIRI_USE_RUST_FOCUS_RING_CORE}>)
if(CC_NIRI_USE_RUST_FOCUS_RING_CORE)
    target_link_libraries(cc-niri-focus-ring-core-backend INTERFACE cc-niri-rust-core)
endif()
