include_guard(GLOBAL)
set(CC_NIRI_USE_RUST_SCROLL_RUNTIME OFF)
option(CC_NIRI_TEST_RUST_SCROLL_RUNTIME "Use Rust Scroll Runtime in integration tests only (R3)" OFF)
message(STATUS "CC-Niri Rust Scroll Runtime backend: ${CC_NIRI_USE_RUST_SCROLL_RUNTIME}")
message(STATUS "CC-Niri Rust Scroll Runtime tests: ${CC_NIRI_TEST_RUST_SCROLL_RUNTIME}")
add_library(cc-niri-rust-scroll STATIC "${CMAKE_CURRENT_LIST_DIR}/../viewport-clip/RustScrollViewportRuntime.cpp")
set_target_properties(cc-niri-rust-scroll PROPERTIES AUTOMOC OFF POSITION_INDEPENDENT_CODE ON)
target_include_directories(cc-niri-rust-scroll PUBLIC "${CMAKE_CURRENT_LIST_DIR}/../viewport-clip")
target_link_libraries(cc-niri-rust-scroll PUBLIC cc-niri-rust-core cc-niri-spring-backend cc-niri-motion-backend Qt6::Core)
add_library(cc-niri-scroll-backend INTERFACE)
target_compile_definitions(cc-niri-scroll-backend INTERFACE
    CC_NIRI_USE_RUST_SCROLL_RUNTIME=$<BOOL:${CC_NIRI_USE_RUST_SCROLL_RUNTIME}>)
if(CC_NIRI_USE_RUST_SCROLL_RUNTIME)
    target_link_libraries(cc-niri-scroll-backend INTERFACE cc-niri-rust-scroll)
endif()
add_library(cc-niri-scroll-test-backend INTERFACE)
target_compile_definitions(cc-niri-scroll-test-backend INTERFACE CC_NIRI_TEST_RUST_SCROLL_RUNTIME=$<BOOL:${CC_NIRI_TEST_RUST_SCROLL_RUNTIME}>)
target_link_libraries(cc-niri-scroll-test-backend INTERFACE cc-niri-scroll-backend cc-niri-rust-scroll)
